//login types
export const LOGIN_ACTION_TYPES = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
    LOGIN_REQUEST_FAIL: 'LOGIN_REQUEST_FAIL',
    LOGOUT_REQUEST_SUCCESS: 'LOGOUT_REQUEST_SUCCESS',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE'
}
//signup types
export const SIGNUP_ACTION_TYPES = {
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_REQUEST_SUCCESS: 'SIGNUP_REQUEST_SUCCESS',
    SIGNUP_REQUEST_FAIL: 'SIGNUP_REQUEST_FAIL'
}


export const LEADLIST_ACTION_TYPES = {
    LEADLIST_REQUEST: 'LEADLIST_REQUEST',
    LEADLIST_REQUEST_SUCCESS: 'LEADLIST_REQUEST_SUCCESS',
    LEADLIST_REQUEST_FAIL: 'LEADLIST_REQUEST_FAIL'
}

export const FORMLEAD_ACTION_TYPES = {
    FORMLEAD_REQUEST: 'FORMLEAD__REQUESt',
    FORMLEAD_REQUEST_SUCCESS: 'FORMLEAD_REQUESt_SUCCESS',
    FORMLEAD_REQUEST_FAIL: 'FORMLEAD_REQUESt_FAIL',
    FORMLEAD_REMOVESUCCESS :'FORMLEAD_REMOVESUCCESS'
}